---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: elastic
  name: es-data
  labels:
    app: elasticsearch
    role: data
spec:
  selector:
    matchLabels:
      app: es-data
      role: data
  serviceName: es-data
  replicas: 1
  template:
    metadata:
      labels:
        app: es-data
        role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      containers:
      - name: es-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: es-data
        - name: NODE_LIST
          value: es-master,es-data,es-client
        - name: MASTER_NODES
          value: es-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms300m -Xmx300m"
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        - name: es-data-pv
          mountPath: /data/db
      volumes:
      - name: config
        configMap:
          name: es-data-config
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: es-data-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi