---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: es
  name: es-data
  labels:
    app: elasticsearch
    role: data
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.zen.ping.unicast.hosts: ["es-master-1:9300", "es-master-2:9300", "es-master-3:9300", "es-data-1:9300", "es-data-2:9300", "es-client-1:9300", "es-client-2:9300"]
    discovery.zen.minimum_master_nodes: 2
    network.host: 0.0.0.0
    node:
      master: false
      data: true
      ingest: false

    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true