---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: es
  name: es-client
  labels:
    app: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: client
  template:
    metadata:
      labels:
        app: elasticsearch
        role: client
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - client
              topologyKey: kubernetes.io/hostname
      containers:
      - name: es-client
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: es-client
        - name: NODE_LIST
          value: es-master,es-data,es-client
        - name: MASTER_NODES
          value: es-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        - name: storage
          mountPath: /data
        - name: es-http-tls
          mountPath: /usr/share/elasticsearch/config/certs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: es-client-config
      - name: "storage"
        emptyDir:
          medium: ""
      - name: es-http-tls
        secret:
          secretName: es-http-tls
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: es
  name: es-client
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: client