---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: elastic
  labels:
    service: kibana-svc
spec:
  type: NodePort
  ports:
  - port: 5601
    name: kibana-svc
    nodePort: 32159
  selector:
    app: kibana