name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
           "/playbooks/*"
           "/roles/*"
           playbook_2.yml
       
        override-deps: |
          ansible==2.10.10
          ansible-lint==4.2.0
        args: ""